### PR TITLE
Support LibreSSL

### PR DESCRIPTION
**Pull request by ghost**
This patch is taken from OpenBSD!

### CODE REVIEW

**Comment by jubalh** [comment]
My guess is that if we have this, libstrophe should have it too.

**Comment by ghost** [comment]
@jubalh ok, done: https://github.com/strophe/libstrophe/pull/134 :)

**Comment by jubalh** [comment]
@mazocomp Thanks!
I'll let @pasis handle this. Or if he merges it on libstrophe I'll merge it here.

**Comment by pasis** [comment]
Hello, I need to understand difference between openssl (different versions) and libressl. Will check it later.

**Comment by ghost** [comment]
@pasis [LibreSSL](https://www.libressl.org/) is OpenBSD's fork of OpenSSL and it's mostly compatible. Its [goals](https://www.libressl.org/goals.html) are:

* Modernize the OpenSSL codebase to make it easier to audit, understand and repair.
* Apply best-practice development processes:
  * Code Review
  * Frequent releases
  * Open development process
* Remove obsolete or broken features and operating system support
* Use and encourage the incorporation of secure programming interfaces in operating systems.
* Provide secure alternatives on operating systems that do not yet have secure programming interfaces available.

**Comment by pasis** [comment]
@mazocomp , thanks for explaining. But I mean the difference in the initialization API. I would like to fully understand correctness of the patch before landing.

**Comment by ghost** [comment]
@pasis oh, unfortunately I am ignorant here, I believe the current maintainer of libstrophe in OpenBSD, Rafael Sadowski @sizeofvoid , can explain you everything you need. (you may also contact him by e-mail rsadowski at openbsd dot org)

**Comment by pasis** [comment]
@mazocomp thank you for advice.

**Comment by sizeofvoid** [comment]
> @mazocomp thank you for advice.

I'll check it out in March after my vacation.

**Comment by pasis** [comment]
I ported solution from nginx to libstrophe: https://github.com/strophe/libstrophe/commit/18b67d6eafbecb8ff3f6cb514594d115e099117d. I like it more since it's localized in a single place. Besides, current patch doesn't build with openssl. I think this PR can be closed after backporting the patch from libstrophe.

**Comment by pasis** [comment]
Merged solution from libstrophe. See 364c8ca60bbab4f869bb0072b55106f9c8a4133d

**Pull request closed without merging**
